baseurl = "https://zempty0.xyz"
title = "Zempty0's Blog"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"

# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = "UA-131829584-1"
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/home-bg-jeep.jpg"
  SEOTitle = "Zempty0's Blog"
  description = "Devops, Open Source, Linux | Here is Yang Lin's blog, and discover the bigger world with you."
  keyword = "zempty0, yanglin, Yanglin, zemtpy0's blog, Zempty0's Blog, blog, Devops"
  slogan = "Road at the foot, heart at the distance"

  image_404 = "img/404-bg.jpg"
  title_404 = "You come to the wasteland without knowledge :("

  # leancloud storage for page view counter
  page_view_conter = true 
  leancloud_app_id = "bF5Y4zC7jFqKKV9P5pPeWIpX-gzGzoHsz"
  leancloud_app_key = "SCoaATSPNOc7C66fI0w9F8Jn"

  # algolia site search
  algolia_search = true
  algolia_appId = "VVCBVQZZHN"
  algolia_indexName = "zempty0_blog"
  algolia_apiKey = "ab111861ad999e74f6ccd32b0a55c443"

  # Sidebar settings
  sidebar_about_description = "Devops, Open Source Enthusiast and Life Adventurer"
  sidebar_avatar = "img/zempty0.png"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 2 

  # Baidu Analytics
  ba_track_id = "e28477a1183b2c0960ac70157fba1a4c"
  
  # We need a proxy to access Disqus api in China
  # disqus_proxy = "https://disqusapi.zhaohuabing.com"
  # disqus_site = "https://zhaohuabing.com"

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = true 

  friends = true
  bookmarks = true
  about_me = true

  [params.social]
  rss            = true 
  email          = "linux0x5c@gmail.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  #linkedin       = "https://www.linkedin.com/in/zhaohuabing"
  #stackoverflow  = "https://stackoverflow.com/users/2306565/huabing-zhao"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/linux0x5c"
  wechat         = "https://zempty0.xyz/img/wechat_qrcode.jpg"
  #medium         = "https://medium.com/@zhaohuabing"
  #pinterest     = "full profile url in pinterest"
  
  [[params.friend_link]]
  title = "Kwen的博客"
  href =  "https://www.kkwen.cn"

  [[params.bookmark_link]]
  title =  "Martin Fowler"
  href =  "https://martinfowler.com"
  [[params.bookmark_link]]
  title = "ServiceMesher"
  href =  "http://www.servicemesher.com"
  [[params.bookmark_link]]
  title = "Awesome Service Mesh"
  href = "https://servicemesh.gitbooks.io/awesome-servicemesh"
  [[params.bookmark_link]]
  title =  "Image Compression"
  href = "https://tinypng.com"
  [[params.bookmark_link]]
  title =  "Pxhere"
  href = "https://pxhere.com"
  [[params.bookmark_link]]
  title = "unsplash"
  href = "https://unsplash.com"
  
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 
